# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: push.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='push.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\npush.proto\"1\n\rSubmitRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0bSubmitReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\x1e\n\x0b\x43onnRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\"\x1f\n\x0cMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t2t\n\x0bMessageSync\x12/\n\rSubmitMessage\x12\x0e.SubmitRequest\x1a\x0c.SubmitReply\"\x00\x12\x34\n\x11PushMessageStream\x12\x0c.ConnRequest\x1a\r.MessageReply\"\x00\x30\x01\x62\x06proto3')
)




_SUBMITREQUEST = _descriptor.Descriptor(
  name='SubmitRequest',
  full_name='SubmitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='SubmitRequest.channel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='SubmitRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=63,
)


_SUBMITREPLY = _descriptor.Descriptor(
  name='SubmitReply',
  full_name='SubmitReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='SubmitReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=93,
)


_CONNREQUEST = _descriptor.Descriptor(
  name='ConnRequest',
  full_name='ConnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='ConnRequest.channel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=125,
)


_MESSAGEREPLY = _descriptor.Descriptor(
  name='MessageReply',
  full_name='MessageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='MessageReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['SubmitRequest'] = _SUBMITREQUEST
DESCRIPTOR.message_types_by_name['SubmitReply'] = _SUBMITREPLY
DESCRIPTOR.message_types_by_name['ConnRequest'] = _CONNREQUEST
DESCRIPTOR.message_types_by_name['MessageReply'] = _MESSAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitRequest = _reflection.GeneratedProtocolMessageType('SubmitRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITREQUEST,
  __module__ = 'push_pb2'
  # @@protoc_insertion_point(class_scope:SubmitRequest)
  ))
_sym_db.RegisterMessage(SubmitRequest)

SubmitReply = _reflection.GeneratedProtocolMessageType('SubmitReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITREPLY,
  __module__ = 'push_pb2'
  # @@protoc_insertion_point(class_scope:SubmitReply)
  ))
_sym_db.RegisterMessage(SubmitReply)

ConnRequest = _reflection.GeneratedProtocolMessageType('ConnRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNREQUEST,
  __module__ = 'push_pb2'
  # @@protoc_insertion_point(class_scope:ConnRequest)
  ))
_sym_db.RegisterMessage(ConnRequest)

MessageReply = _reflection.GeneratedProtocolMessageType('MessageReply', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEREPLY,
  __module__ = 'push_pb2'
  # @@protoc_insertion_point(class_scope:MessageReply)
  ))
_sym_db.RegisterMessage(MessageReply)



_MESSAGESYNC = _descriptor.ServiceDescriptor(
  name='MessageSync',
  full_name='MessageSync',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=160,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitMessage',
    full_name='MessageSync.SubmitMessage',
    index=0,
    containing_service=None,
    input_type=_SUBMITREQUEST,
    output_type=_SUBMITREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PushMessageStream',
    full_name='MessageSync.PushMessageStream',
    index=1,
    containing_service=None,
    input_type=_CONNREQUEST,
    output_type=_MESSAGEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGESYNC)

DESCRIPTOR.services_by_name['MessageSync'] = _MESSAGESYNC

# @@protoc_insertion_point(module_scope)
